# Generated by Django 3.0.4 on 2020-03-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200324_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ID', 'Indoor'), ('OD', 'Outdoor')], max_length=100, null=True),
        ),
    ]
